server:
  port: 8082
spring:
  application:
    name: tech-challenge-production
  datasource:
    url: >-
      jdbc:mysql://${DB_SERVER}/${DB_NAME}?useTimezone=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: com.techchallenge.config.MysqlCustomDialect
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}

kafka:
  topic:
    producer:
      status: status.order
    consumer:
      orders:
        topic: tech.orders
        groupId: production9
      payment:
        topic: tech.payment
        groupId: groupPayment

