server:
  port: 8083
spring:
  application:
    name: tech-challenge-production
  datasource:
    url: >-
      jdbc:mysql://localhost:3306/production?useTimezone=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dani
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: com.techchallenge.config.MysqlCustomDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092

kafka:
  topic:
    producer:
      orders: status.order
    consumer:
      orders:
        topic: tech.orders
        groupId: production9
      payment:
        topic: tech.payment
        groupId: groupPayment
