apiVersion: v1
kind: Service
metadata:
  name: production
  labels:
    app: production
spec:
  type: NodePort
  selector:
    app: production
  ports:
    - protocol: TCP
      name: http
      port: 8082
      targetPort: 8082
      nodePort: 30007