apiVersion: apps/v1
kind: Deployment
metadata:
  name: production
  labels:
    app: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: production
  template:
    metadata:
      labels:
        app: production
    spec:
      containers:
      - name: production
        image: daniel36/tech-challenge-production:02
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8082
        resources:
          limits:
            cpu: 0.2
            memory: "512Mi"
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: mysql-user-password
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: mysql-server
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: mysql-database-name
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: mysql-user-username

        - name: DB_NAME
          value: production

        - name: KAFKA_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config-map
              key: kafka-servers

---
